export const endpoints = {
    auth: {
        login: "/staff-auth/login",
        register: "/staff",
        me: "/staff-auth/session",
        changePassword: "/staff-auth/change-password",
        logout: "/staff-auth/logout",
    },
    configuracion: "/configuracion",
    usuarios: "/staff",
    clientes: "/clientes",
    revendedores: "/revendedores",
    proveedores: "/proveedores",
    categorias: "/categorias",
    productos: "/productos",
    variantes: "/variantes",
    proveedoresProductos: "/proveedores-productos",
    cuentas: "/cuentas",
    keys: "/keys",
    ventas: "/ventas",
    detalleVentas: "/detalle-ventas",
    compras: "/compras",
    detalleCompras: "/detalle-compras",
    gastos: "/gastos",
    renovaciones: "/renovaciones",
    tareas: "/tareas",
    calendario: "/calendario",
    dashboard: "/dashboard",
    plantillas: "/plantillas",
};

export default endpoints;
